

services:

  # Backend (Node/Express)
  backend:
    build:
      context: ./backend
    container_name: focusly-backend
    restart: unless-stopped
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    networks:
      - focusly-network

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: focusly-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - focusly-network

networks:
  focusly-network:
    driver: bridge